/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ResultsLazyImport = createFileRoute('/results')()
const FormLazyImport = createFileRoute('/form')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ResultsLazyRoute = ResultsLazyImport.update({
  path: '/results',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/results.lazy').then((d) => d.Route))

const FormLazyRoute = FormLazyImport.update({
  path: '/form',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/form.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormLazyImport
      parentRoute: typeof rootRoute
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/form': typeof FormLazyRoute
  '/results': typeof ResultsLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/form': typeof FormLazyRoute
  '/results': typeof ResultsLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/form': typeof FormLazyRoute
  '/results': typeof ResultsLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/form' | '/results'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/form' | '/results'
  id: '__root__' | '/' | '/form' | '/results'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  FormLazyRoute: typeof FormLazyRoute
  ResultsLazyRoute: typeof ResultsLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  FormLazyRoute: FormLazyRoute,
  ResultsLazyRoute: ResultsLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/form",
        "/results"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/form": {
      "filePath": "form.lazy.tsx"
    },
    "/results": {
      "filePath": "results.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
